# Generated by Django 4.2.23 on 2025-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('qr_code_uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField()),
            ],
        ),
    ]
